apiVersion: v1
kind: Service
metadata:
  name: landing-app-service
  labels:
    app: landing-app
spec:
  selector:
    app: landing-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer